# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bolt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.tensorflow.core.framework import tensor_pb2 as proto_dot_tensorflow_dot_core_dot_framework_dot_tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/bolt.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10proto/bolt.proto\x1a,proto/tensorflow/core/framework/tensor.proto\"\x16\n\x05Words\x12\r\n\x05words\x18\x01 \x03(\t26\n\x04\x42olt\x12.\n\x05Spike\x12\x06.Words\x1a\x1b.bolttensorflow.TensorProto\"\x00\x62\x06proto3')
  ,
  dependencies=[proto_dot_tensorflow_dot_core_dot_framework_dot_tensor__pb2.DESCRIPTOR,])




_WORDS = _descriptor.Descriptor(
  name='Words',
  full_name='Words',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='words', full_name='Words.words', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Words'] = _WORDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Words = _reflection.GeneratedProtocolMessageType('Words', (_message.Message,), dict(
  DESCRIPTOR = _WORDS,
  __module__ = 'proto.bolt_pb2'
  # @@protoc_insertion_point(class_scope:Words)
  ))
_sym_db.RegisterMessage(Words)



_BOLT = _descriptor.ServiceDescriptor(
  name='Bolt',
  full_name='Bolt',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=90,
  serialized_end=144,
  methods=[
  _descriptor.MethodDescriptor(
    name='Spike',
    full_name='Bolt.Spike',
    index=0,
    containing_service=None,
    input_type=_WORDS,
    output_type=proto_dot_tensorflow_dot_core_dot_framework_dot_tensor__pb2._TENSORPROTO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOLT)

DESCRIPTOR.services_by_name['Bolt'] = _BOLT

# @@protoc_insertion_point(module_scope)
