# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bolt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/bolt.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10proto/bolt.proto\"a\n\x0cSpikeRequest\x12\x17\n\x0fsender_identity\x18\x01 \x01(\t\x12\x18\n\x10message_identity\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\r\n\x05shape\x18\x04 \x03(\x05\"e\n\rSpikeResponse\x12\x1a\n\x12responder_identity\x18\x01 \x01(\t\x12\x18\n\x10message_identity\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\r\n\x05shape\x18\x04 \x03(\x05\"n\n\x0cGradeRequest\x12\x17\n\x0fsender_identity\x18\x01 \x01(\t\x12\x18\n\x10message_identity\x18\x02 \x01(\t\x12\x15\n\rspike_payload\x18\x03 \x01(\x0c\x12\x14\n\x0cgrad_payload\x18\x04 \x01(\x0c\"\x1f\n\rGradeResponse\x12\x0e\n\x06\x61\x63\x63\x65pt\x18\x01 \x01(\x08\x32Z\n\x04\x42olt\x12(\n\x05Spike\x12\r.SpikeRequest\x1a\x0e.SpikeResponse\"\x00\x12(\n\x05Grade\x12\r.GradeRequest\x1a\x0e.GradeResponse\"\x00\x62\x06proto3')
)




_SPIKEREQUEST = _descriptor.Descriptor(
  name='SpikeRequest',
  full_name='SpikeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender_identity', full_name='SpikeRequest.sender_identity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_identity', full_name='SpikeRequest.message_identity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='SpikeRequest.payload', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='SpikeRequest.shape', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=117,
)


_SPIKERESPONSE = _descriptor.Descriptor(
  name='SpikeResponse',
  full_name='SpikeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responder_identity', full_name='SpikeResponse.responder_identity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_identity', full_name='SpikeResponse.message_identity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='SpikeResponse.payload', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='SpikeResponse.shape', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=220,
)


_GRADEREQUEST = _descriptor.Descriptor(
  name='GradeRequest',
  full_name='GradeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender_identity', full_name='GradeRequest.sender_identity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_identity', full_name='GradeRequest.message_identity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spike_payload', full_name='GradeRequest.spike_payload', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grad_payload', full_name='GradeRequest.grad_payload', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=332,
)


_GRADERESPONSE = _descriptor.Descriptor(
  name='GradeResponse',
  full_name='GradeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accept', full_name='GradeResponse.accept', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=365,
)

DESCRIPTOR.message_types_by_name['SpikeRequest'] = _SPIKEREQUEST
DESCRIPTOR.message_types_by_name['SpikeResponse'] = _SPIKERESPONSE
DESCRIPTOR.message_types_by_name['GradeRequest'] = _GRADEREQUEST
DESCRIPTOR.message_types_by_name['GradeResponse'] = _GRADERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpikeRequest = _reflection.GeneratedProtocolMessageType('SpikeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SPIKEREQUEST,
  '__module__' : 'proto.bolt_pb2'
  # @@protoc_insertion_point(class_scope:SpikeRequest)
  })
_sym_db.RegisterMessage(SpikeRequest)

SpikeResponse = _reflection.GeneratedProtocolMessageType('SpikeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPIKERESPONSE,
  '__module__' : 'proto.bolt_pb2'
  # @@protoc_insertion_point(class_scope:SpikeResponse)
  })
_sym_db.RegisterMessage(SpikeResponse)

GradeRequest = _reflection.GeneratedProtocolMessageType('GradeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRADEREQUEST,
  '__module__' : 'proto.bolt_pb2'
  # @@protoc_insertion_point(class_scope:GradeRequest)
  })
_sym_db.RegisterMessage(GradeRequest)

GradeResponse = _reflection.GeneratedProtocolMessageType('GradeResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRADERESPONSE,
  '__module__' : 'proto.bolt_pb2'
  # @@protoc_insertion_point(class_scope:GradeResponse)
  })
_sym_db.RegisterMessage(GradeResponse)



_BOLT = _descriptor.ServiceDescriptor(
  name='Bolt',
  full_name='Bolt',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=367,
  serialized_end=457,
  methods=[
  _descriptor.MethodDescriptor(
    name='Spike',
    full_name='Bolt.Spike',
    index=0,
    containing_service=None,
    input_type=_SPIKEREQUEST,
    output_type=_SPIKERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Grade',
    full_name='Bolt.Grade',
    index=1,
    containing_service=None,
    input_type=_GRADEREQUEST,
    output_type=_GRADERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOLT)

DESCRIPTOR.services_by_name['Bolt'] = _BOLT

# @@protoc_insertion_point(module_scope)
