# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bolt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.tensorflow.core.framework import tensor_pb2 as proto_dot_tensorflow_dot_core_dot_framework_dot_tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/bolt.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10proto/bolt.proto\x1a,proto/tensorflow/core/framework/tensor.proto2K\n\x04\x42olt\x12\x43\n\x05Spike\x12\x1b.bolttensorflow.TensorProto\x1a\x1b.bolttensorflow.TensorProto\"\x00\x62\x06proto3')
  ,
  dependencies=[proto_dot_tensorflow_dot_core_dot_framework_dot_tensor__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BOLT = _descriptor.ServiceDescriptor(
  name='Bolt',
  full_name='Bolt',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=66,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='Spike',
    full_name='Bolt.Spike',
    index=0,
    containing_service=None,
    input_type=proto_dot_tensorflow_dot_core_dot_framework_dot_tensor__pb2._TENSORPROTO,
    output_type=proto_dot_tensorflow_dot_core_dot_framework_dot_tensor__pb2._TENSORPROTO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOLT)

DESCRIPTOR.services_by_name['Bolt'] = _BOLT

# @@protoc_insertion_point(module_scope)
