
# (str) Visualizer script.
script: ./visualizer/visualizer.sh

# (int) Seconds between refresh.
heartbeat: 5

# (str) Visualization mode
visualization_mode: tensorboard

# (str) The address to bind the visualizer server.
bind_address: 0.0.0.0

# (str) The visualizer serving port.
port: 14142

# (str) The tensorboard serving port.
tbport: 14143

# (str) Visualizer logging directory.
logdir: data/visualizer/logs

# (str) BitTensor contract account on EOS
eos:
  account: bittensoracc

  # (str) Contract scope.
  scope: bittensoracc

  # (str) EOS contract code name.
  code: bittensoracc

  # (str) EOS table which stores metagraph information.
  table: metagraph

  # (str) EOS chain key type.
  key_type: i64

  # (str) URL of EOS chain.
  url: http://host.docker.internal:8888

  # (str) EOS endpoint command.
  get_table_command: /v1/chain/get_table_rows
