# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bolt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bolt.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nbolt.proto\"\x15\n\x05thing\x12\x0c\n\x04word\x18\x01 \x01(\t2 \n\x04\x42olt\x12\x18\n\x04Test\x12\x06.thing\x1a\x06.thing\"\x00\x62\x06proto3')
)




_THING = _descriptor.Descriptor(
  name='thing',
  full_name='thing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='thing.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=35,
)

DESCRIPTOR.message_types_by_name['thing'] = _THING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

thing = _reflection.GeneratedProtocolMessageType('thing', (_message.Message,), dict(
  DESCRIPTOR = _THING,
  __module__ = 'bolt_pb2'
  # @@protoc_insertion_point(class_scope:thing)
  ))
_sym_db.RegisterMessage(thing)



_BOLT = _descriptor.ServiceDescriptor(
  name='Bolt',
  full_name='Bolt',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=37,
  serialized_end=69,
  methods=[
  _descriptor.MethodDescriptor(
    name='Test',
    full_name='Bolt.Test',
    index=0,
    containing_service=None,
    input_type=_THING,
    output_type=_THING,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOLT)

DESCRIPTOR.services_by_name['Bolt'] = _BOLT

# @@protoc_insertion_point(module_scope)
