# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bolt_pb2 as bolt__pb2


class BoltStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Test = channel.unary_unary(
        '/Bolt/Test',
        request_serializer=bolt__pb2.thing.SerializeToString,
        response_deserializer=bolt__pb2.thing.FromString,
        )


class BoltServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BoltServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Test': grpc.unary_unary_rpc_method_handler(
          servicer.Test,
          request_deserializer=bolt__pb2.thing.FromString,
          response_serializer=bolt__pb2.thing.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Bolt', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
